version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "itemize_mongodb"
        environment:
          - MONGO_DATA_DIR=/mongodata/db
          - MONGO_LOG_DIR=/mongodev/null
        volumes:
          - ./mongodata/db:/mongodata/db
        ports:
            - 27017:27017
        command: mongod 